### PR TITLE
Openmp: Try using FindOpenMP again

### PR DESCRIPTION
**Pull request by 1480c1**
https://github.com/georgmartius/vid.stab/commit/ce0ea9ac5edcdc568a72ee169b800e39a6c543c6

as mentioned here, the previous attempt needed to be reverted

### CODE REVIEW

**Comment by martius-lab** [comment]
How is the status of this? I didn't follow up on this. The FindOpenMP was not available for older CMake versions, right?

**Comment by georgmartius** [comment]
How is the status of this? I didn't follow up on this. The FindOpenMP was not available for older CMake versions, right?

**Comment by 1480c1** [comment]
For now, it's working on Ubuntu 20.04 gcc and clang and mingw-w64 gcc and mingw-w64 clang

FindOpenMP is listed under cmake's doc for 2.8.5 (the required version I see in the CMakeLists.txt) https://cmake.org/cmake/help/v2.8.5/cmake.html#module:FindOpenMP

I think @ddennedy said it's working on his machines, except macOS, and I don't remember if I heard a followup on if there were any new issues

I am considering instead adding a small compile and link test to the CMakeLists to make sure that the found flags for openmp actually work, but I am not sure if it will be completely worth the added complexity. Do you have any comments or suggestion on that part?

**Comment by ddennedy** [comment]
I approve of merging this. FYI, upon further troubleshooting here is the interesting problem I had. I am building vid.stab on macOS with gcc and libgomp because Xcode does not include OpenMP. This puts a `-fopenmp` into the png-config file. Later when I link my code that is built with the default compiler - clang from Xcode - against vid.stab it does not understand that flag. :-S

**Pull request merged**
