### PR TITLE
check availability of SSE* instructions on target platform

### PR DESCRIPTION
**Pull request by Karry**
Checking sse instructions on build host by reading /proc/cpuinfo
is not usable for crosscompilation. 

Fix for https://github.com/georgmartius/vid.stab/issues/109

### CODE REVIEW

**Comment by georgmartius** [comment]
Hi Karry,
thanks for fixing this. On which platforms have you tried it so far?

**Comment by Karry** [comment]
I tried it on armv7l (directly on hardware) and aarch64 crosscompilation. And of course on x86_64.

**Comment by georgmartius** [comment]
Wonderful.

**Comment by georgmartius** [comment]
I was running the checks and they failed. Can you also see them? If I understand correctly, the cmakefile in the test folder also need adaptation, right?

**Comment by Karry** [comment]
It is good to have CI builds ;-) It is just necessary to replace `PROJECT_SOURCE_DIR` by `CMAKE_CURRENT_LIST_DIR`

**Pull request merged**
