### PR TITLE
Obliterating most any reference to ORC

### PR DESCRIPTION
**Pull request by thinrope**
This should clean the code and fix issue #95 ... I have completely forgotten it hangs on me for 4 years... 

I did my best to make sure things work, but @georgmartius please have a look too, it was a lot more code to remove than I expected. If you are fine with all that, I think we can try to push a new version, so it can get packaged at some point.

It caused quite a stir at https://github.com/gentoo/gentoo/pull/35264, since I have completely forgotten about this issue.

Bug: https://github.com/georgmartius/vid.stab/issues/95
Signed-off-by:Kalin KOZHUHAROV <kalin@thinrope.net>
Related: https://bugs.gentoo.org/927886

### CODE REVIEW

**Comment by thinrope** [comment]
Hi @georgmartius, I know you are busy, but since nobody uses this part of the code and it causes issues, can we have it removed? And may be pimp a few other things and release something in 2024?

**Comment by georgmartius** [comment]
Hi, thanks for investing time. Okay, I promise to do something on this repo in 1 month. Feel free to ping me again ;-).

**Comment by thinrope** [comment]
Hi @georgmartius, pinging you as requested ;-) Let's give this code a bit of love :-)

**Comment by thinrope** [comment]
Hi @georgmartius, re-pinging you...

**Comment by georgmartius** [comment]
Sorry, I somehow misunderstood. This merge request looks good. Sure, let's get rid of some old stuff. 
I was thinking of more stuff to be done, which I cannot do at the moment, but hope to get at in August.

**Comment by georgmartius** [comment]
If we require a version bump, please also prepare a pull request, I will then do that ASAP.

**Pull request merged**
